language: node_js
sudo: false
node_js:
  - "7.0"
install:
  - npm install -g codecov istanbul
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec && codecov
  - codecov
