language: node_js
sudo: false
node_js:
  - "7.0"
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm test
  - istanbul cover /home/travis/build/alaninchika/aws-ec2/node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
