Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    AWSEC2:
        Description: "A microservice for AWS elastic compute cloud."
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    EC2LambdaTrustRole:
        Description: Creating service role in IAM for AWS Lambda
        Type: AWS::IAM::Role
        Properties:
            RoleName: ec2LambdaRole
            AssumeRolePolicyDocument:
                Statement:
                - Effect: Allow
                  Principal:
                    Service: [lambda.amazonaws.com]
                  Action: sts:AssumeRole
            Path: /
            Policies:
            - PolicyName: ec2LambdaRolePolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: ["ec2:StartInstances", "ec2:StopInstances"]
                  Resource: ["arn:aws:ec2:*:*:instance/*"]
                - Effect: Allow
                  Action: ["ec2:DescribeInstanceStatus"]
                  Resource: ["*"]
    EC2Microservice:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Role: !GetAtt EC2LambdaTrustRole.Arn
            Runtime: nodejs8.10
            CodeUri: ./
            Environment:
                Variables:
                    ORIGIN_URL: !Ref OriginUrl
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /ec2
                  Method: get
